name: Build and Deploy

on:
  push:
    branches:
      - main # 你希望在推送到哪个分支时触发这个工作流程

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: "8"
          distribution: "adopt" # 可以选择合适的JDK发行版，如 zulu, adopt, temurin
          cache: maven

      - name: maven build
        run: mvn clean package

      - name: Deploy to remote server
        env:
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        run: |
          ssh -i $DEPLOY_KEY -o StrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_HOST "mkdir -p /path/to/deploy"
          scp -i $DEPLOY_KEY -o StrictHostKeyChecking=no target/your-app.jar $DEPLOY_USER@$DEPLOY_HOST:/path/to/deploy/

      # 可选：在部署后重启远程服务器上的服务
      - name: Restart remote service
        if: success()
        env:
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        run: |
          ssh -i $DEPLOY_KEY -o StrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_HOST "sudo systemctl restart your-service"
