name: Pull and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  pull-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Pull and Push Docker Images
      run: |
        DOCKER_REPO_URL="${{ secrets.DOCKER_REPO_URL }}"
        while IFS=: read -r image arch; do
          arch="${arch:-amd64}"  # 默认架构为amd64
          echo "Processing image: $image for architecture: $arch"
          docker pull --platform linux/$arch "$image"
          image_name="$(basename $image)"
          docker tag "$image" "$DOCKER_REPO_URL/$image_name:$arch"
          docker push "$DOCKER_REPO_URL/$image_name:$arch"
        done < images.txt
